travis:
  secure:
    BINSTAR_TOKEN: 5DAXPk8ya9jbmRE/E9ZfDuNWwPg9lb4+Xwh9yI6x0TC3TZaIf+G8dMYYjIbUtlMC0cmlzOpunZ9hNctHYJmCjZbmdRCBWuuIa3LPITRPKGuCDfclGQyP7OOOAZLExH/h1iQBrIt/Vd2t9CI6m7Vm7IHSOOlMcV465RvF5ZXS4DAlkBR7UiUpBn9QEnGIcnyO4rf8GMKaP8zE+G/ZNSucDzgYRk1hzF2PHWG06ss66ncYoB+DxvhqUfmBNTWGnPJgLSEDSdM/BhpA/+ATf+OGkWRus/ZoHzn3qaojLzcCRKwFfycjtiUpLA95HAkqjCWKIwG9LVN6ipDNqSE9tKvbLyfcTSIChfEYqnpPgJq2d4WxEcpXF/7y3Eyf0182dxMzoXY+bi0ayQ6gmjAFHy+YlCdOiFFDMO2E/Fcy/+aVz2V5gLDYbeZaFmL4c90HxTUCuyl1v/WMD2ByhxEFL3kc1O7exdIINM4z+OnzmG/03z3Qd66ZHmun97St3BoUMioWIcnRAzGDTFp9YaOxEuhS1aATSy1QU7AplPj90fKO/L7f6srFvlbV3UeDa24rwhDvIJ6Ea+5Ub6FK7N0Z9rwq9u73550OlBh+rtCnGENpDgRmKV9dP1WAmHGJIKp6bxBD7j60zxYPW4BJ4ntrmrrdS6UcLFVUCiyEqodf2Y1wLbE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
